### PR TITLE
Add guard to transition

### PR DESCRIPTION
**Pull request by viniciuslcpereira97**
This PR allows Machinist to define "guards" to validate if an structure should transit between states or not in a more semanthic and visible way.

## Example
```ex
defmodule StateMachineExample do
  transitions do
    from(:created,
      to: :awaiting_confirmation,
      guard: &send_confirmation/1,
      event: "activate"
    )

    from(:awaiting_confirmation,
      to: :confirmed,
      guard: &was_confirmed?/1,
      event: "activate"
    )

    from(:confirmed,
      to: :active,
      event: "activate"
    )
  end

  def send_confirmation(_current_state), do: true

  def was_confirmed?(_current_state), do: false
end
```

Currently, it's required to define guard functions with `arity` 1, the received argument is the current state structure.

### CODE REVIEW

**Comment by viniciuslcpereira97** [comment]
@norbajunior just created the new pull request.

Is there adjustments i should do to make it eligible for the repository?

**Comment by viniciuslcpereira97** [comment]
@norbajunior just created the new pull request.

Are there changes that I need to make for the pull request to be in compliance with the repository?

**Comment by norbajunior** [comment]
Sorry for the delay [@viniciuslcpereira97](https://github.com/viniciuslcpereira97). I was reflecting on your purpose because the lib already has the `guard` condition attached to the `event` macro which can direct to more than just two conditional flows. Aiming to match a state machine graph. I'm unsure if a guard should be an option to `from` macro 🤔.

Is your example a real one? I was thinking of reformulating it to something like the below, whereas the lib already meets the requirements:

```mermaid
stateDiagram-v2
    [*] --> created
    created --> awaiting_confirmation : confirmation_sent
    state if_state <<choice>>
    awaiting_confirmation --> confirmed? : activate
    confirmed? --> if_state
    if_state --> registered : true
    if_state --> created : false
    registered --> [*]
```

Is this similar?

In the first transition (created -> awaiting_confirmation), the event may be `confirmation_sent`, and sending the confirmation should be separate from the state machine flow. 

```elixir
defmodule User do
  defstruct [state: :created]

  use Machinist

  transitions do
    from :created, to: :awaiting_confirmation, event: "create"

    event "confirm", guard: &confirmed?/1 do
      from :awaiting_confirmation, to: :registered
    end 
  end

  defp confirmed?(user) do
    if Users.account_confirmed?(user) do
      :registered
    else
      {:error, "The account has not been confirmed yet"}
    end
  end
end
```

I was stressing the possibilities, and I think we should keep elsewhere things not associated with state changes, such as sending confirmation. The good practice is just using the guard function to check a condition and return the next state or a transition error.

Does it make sense? Let me know if I missed something here.

**Comment by norbajunior** [comment]
I'm closing this PR due to a long inactivity. Please if you want to discuss this further reopen it.

**Pull request closed without merging**
